'use strict';

import { createSupabaseClient } from './src/infrastructure/supabase/supabase-client.js';

const client=createSupabaseClient({config:window.AVAN_CONFIG||{},storage:localStorage});
const authState=document.getElementById('platformAuthState');
const content=document.getElementById('platformContent');
const kpis=document.getElementById('platformKpis');
const companyRows=document.getElementById('companyRows');
const auditHost=document.getElementById('platformAudit');
const companySearch=document.getElementById('companySearch');
const refreshButton=document.getElementById('refreshPlatform');
let companies=[];let platformRole='';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const faNumber=v=>Number(v||0).toLocaleString('fa-IR');
function faDate(v){if(!v)return'—';try{return new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return'—'}}
function option(value,current,label,disabled=false){return`<option value="${esc(value)}" ${value===current?'selected':''} ${disabled?'disabled':''}>${esc(label)}</option>`}
function selectOptions(kind,current){if(kind==='status')return option('active',current,'فعال')+option('onboarding',current,'راه‌اندازی')+option('suspended',current,'تعلیق')+option('archived',current,'آرشیو',platformRole!=='platform_owner');if(kind==='plan')return option('trial',current,'آزمایشی')+option('core',current,'Core')+option('pro',current,'Pro')+option('enterprise',current,'Enterprise')+option('custom',current,'سفارشی');if(kind==='onboarding')return option('not_started',current,'شروع نشده')+option('in_progress',current,'در حال انجام')+option('blocked',current,'مسدود')+option('ready',current,'آماده')+option('completed',current,'تکمیل');return option('none',current,'بدون درخواست')+option('open',current,'باز')+option('in_progress',current,'در حال پیگیری')+option('waiting_customer',current,'منتظر مشتری')+option('resolved',current,'حل‌شده')}
function setAuthState(text,kind=''){authState.textContent=text;authState.className=`state-card ${kind}`.trim()}
function registryLabel(v){return({ok:'سالم',missing_owner:'مالک ثبت نشده',missing_owner_user:'حساب مالک موجود نیست'})[v]||'نیازمند بررسی'}
function renderKpis(d={}){const items=[['کل شرکت‌ها',d.companies_total],['فعال',d.companies_active],['تعلیق',d.companies_suspended],['کاربران',d.users_total],['پشتیبانی فعال',d.active_support_sessions],['پشتیبانی باز',d.support_open],['عضویت فعال',d.active_memberships],['ادمین پلتفرم',d.platform_admins_active]];kpis.innerHTML=items.map(([l,v])=>`<article class="kpi"><span>${esc(l)}</span><strong>${faNumber(v)}</strong></article>`).join('')}

function supportControls(c){const s=c.active_support_session;if(s)return`<div class="support-box active-support"><strong>Support فعال · فقط‌خواندنی</strong><small>انقضا: ${esc(faDate(s.expires_at))}</small><small>${esc(s.reason||'')}</small><div class="support-actions"><a class="ghost small" href="support-viewer.html?session=${encodeURIComponent(s.session_id)}">بازکردن Viewer</a><button class="ghost small danger" data-revoke-support="${esc(s.session_id)}">لغو دسترسی</button></div></div>`;return`<div class="support-box"><strong>دسترسی پشتیبانی</strong><div class="support-create"><select data-support-duration><option value="15">۱۵ دقیقه</option><option value="30">۳۰ دقیقه</option><option value="60">۶۰ دقیقه</option></select><textarea data-support-reason rows="2" maxlength="500" placeholder="دلیل دسترسی پشتیبانی (حداقل ۱۰ نویسه)"></textarea><button class="ghost small" data-create-support="${esc(c.company_id)}">شروع Support فقط‌خواندنی</button></div></div>`}

function renderCompanies(filter=''){const q=String(filter||'').trim().toLowerCase();const rows=companies.filter(c=>!q||[c.display_name,c.name,c.legal_name,c.owner_email,c.plan_code,c.status].some(v=>String(v||'').toLowerCase().includes(q)));companyRows.innerHTML=rows.length?rows.map(c=>{const ok=c.registry_state==='ok';return`<tr data-company-row="${esc(c.company_id)}"><td><div class="company-name"><strong>${esc(c.display_name||c.name||'شرکت بدون نام')}</strong><small>${esc(c.owner_email||'مالک نامشخص')}</small></div></td><td><div class="member-limit"><span>${faNumber(c.active_members)} فعال</span><input data-field="member_limit" type="number" min="1" max="10000" value="${Number(c.member_limit||10)}"></div></td><td><select data-field="status">${selectOptions('status',c.status)}</select><small>${c.access_allowed?'دسترسی باز':'دسترسی بسته'}</small></td><td><select data-field="plan_code">${selectOptions('plan',c.plan_code||'core')}</select></td><td><select data-field="onboarding_state">${selectOptions('onboarding',c.onboarding_state||'completed')}</select></td><td><select data-field="support_state">${selectOptions('support',c.support_state||'none')}</select></td><td><span class="badge ${ok?'ok':'bad'}">${esc(registryLabel(c.registry_state))}</span></td><td class="operation-cell"><textarea data-field="reason" rows="2" maxlength="500" placeholder="دلیل تغییر Tenant (الزامی)"></textarea><button class="primary small" data-save-company="${esc(c.company_id)}">ثبت عملیات</button><span class="row-status" aria-live="polite"></span>${supportControls(c)}</td></tr>`}).join(''):'<tr><td colspan="8" class="empty">موردی پیدا نشد.</td></tr>';bindActions()}
function renderAudit(rows=[]){auditHost.innerHTML=rows.length?rows.map(r=>`<div class="audit-item"><div><strong>${esc(r.summary||r.action)}</strong><span>${esc(r.action||'')}${r.tenant_id?` · Tenant ${esc(r.tenant_id)}`:''}</span></div><time>${esc(faDate(r.created_at))}</time></div>`).join(''):'<div class="empty">هنوز رویدادی ثبت نشده است.</div>'}

async function saveCompany(id,button){const row=button.closest('[data-company-row]');const get=n=>row.querySelector(`[data-field="${n}"]`);const status=row.querySelector('.row-status');const reason=String(get('reason')?.value||'').trim();if(reason.length<5){status.textContent='دلیل حداقل ۵ نویسه الزامی است.';return}button.disabled=true;status.textContent='در حال ثبت…';try{await client.rpc('platform_admin_update_tenant',{p_company_id:id,p_status:get('status').value,p_plan_code:get('plan_code').value,p_member_limit:Number(get('member_limit').value),p_onboarding_state:get('onboarding_state').value,p_support_state:get('support_state').value,p_reason:reason});status.textContent='ثبت شد.';await load({logEntry:false})}catch(e){status.textContent=String(e?.message||'').includes('PLATFORM_OWNER_REQUIRED')?'آرشیو فقط برای مالک پلتفرم مجاز است.':'عملیات ثبت نشد.'}finally{button.disabled=false}}
async function createSupport(id,button){const row=button.closest('[data-company-row]');const reason=String(row.querySelector('[data-support-reason]')?.value||'').trim();const mins=Number(row.querySelector('[data-support-duration]')?.value||15);const status=row.querySelector('.row-status');if(reason.length<10){status.textContent='دلیل Support حداقل ۱۰ نویسه باشد.';return}button.disabled=true;status.textContent='در حال ایجاد Support…';try{const s=await client.rpc('platform_admin_create_support_session',{p_company_id:id,p_duration_minutes:mins,p_reason:reason});status.textContent='Support فقط‌خواندنی فعال شد.';await load({logEntry:false});if(s?.session_id)window.open(`support-viewer.html?session=${encodeURIComponent(s.session_id)}`,'_blank','noopener')}catch(e){const m=String(e?.message||'');status.textContent=m.includes('SUPPORT_SESSION_ALREADY_ACTIVE')?'برای این شرکت Session فعال وجود دارد.':'Support ایجاد نشد.'}finally{button.disabled=false}}
async function revokeSupport(sessionId,button){if(!confirm('دسترسی پشتیبانی فوراً لغو شود؟'))return;button.disabled=true;try{await client.rpc('platform_admin_revoke_support_session',{p_session_id:sessionId,p_reason:'لغو دستی توسط ادمین سامانه آوان'});await load({logEntry:false})}catch{alert('لغو Session انجام نشد.')}finally{button.disabled=false}}
function bindActions(){companyRows.querySelectorAll('[data-save-company]').forEach(b=>b.onclick=()=>saveCompany(b.dataset.saveCompany,b));companyRows.querySelectorAll('[data-create-support]').forEach(b=>b.onclick=()=>createSupport(b.dataset.createSupport,b));companyRows.querySelectorAll('[data-revoke-support]').forEach(b=>b.onclick=()=>revokeSupport(b.dataset.revokeSupport,b))}

async function load({logEntry=true}={}){if(refreshButton)refreshButton.disabled=true;setAuthState('در حال بررسی دسترسی ادمین کل…');content.hidden=true;try{const user=await client.user();if(!user?.id){setAuthState('ابتدا در آوان وارد حساب کاربری شوید.','error');return}const me=await client.rpc('platform_admin_me',{});if(!me?.authorized){setAuthState('این حساب Platform Admin نیست.','error');return}platformRole=me.role||'';if(logEntry)await client.rpc('platform_admin_enter',{});const [overview,list,audit]=await Promise.all([client.rpc('platform_admin_overview',{}),client.rpc('platform_admin_companies',{}),client.rpc('platform_admin_audit',{p_limit:50})]);companies=Array.isArray(list)?list:[];renderKpis(overview||{});renderCompanies(companySearch?.value||'');renderAudit(Array.isArray(audit)?audit:[]);content.hidden=false;setAuthState(`دسترسی تأیید شد — ${platformRole==='platform_owner'?'مالک پلتفرم':'ادمین پلتفرم'}. Support فقط با Session موقت و Read-only باز می‌شود.`,'ok')}catch(e){console.error(e);setAuthState('بارگذاری Control Plane انجام نشد.','error')}finally{if(refreshButton)refreshButton.disabled=false}}
if(companySearch)companySearch.addEventListener('input',()=>renderCompanies(companySearch.value));if(refreshButton)refreshButton.onclick=()=>load({logEntry:false});load();
