-- Avan RC1.3-MT-P1 — Platform Admin Control Plane Skeleton
-- ADR-0014 / ADR-0015
-- Control Plane is metadata-only and is NOT a tenant-ledger access path.

begin;

create schema if not exists private;

grant usage on schema private to authenticated;

create table if not exists private.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'platform_admin'
    check (role in ('platform_owner','platform_admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users(id)
);

alter table private.platform_admins enable row level security;
revoke all on table private.platform_admins from public, anon, authenticated;

create table if not exists private.platform_tenants (
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  status text not null default 'active'
    check (status in ('onboarding','active','suspended','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table private.platform_tenants enable row level security;
revoke all on table private.platform_tenants from public, anon, authenticated;

insert into private.platform_tenants(workspace_id,status,created_at,updated_at)
select w.id,'active',w.created_at,now()
from public.workspaces w
on conflict (workspace_id) do nothing;

create table if not exists private.platform_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid null references auth.users(id) on delete set null,
  action text not null,
  tenant_id uuid null references public.workspaces(id) on delete set null,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table private.platform_audit_logs enable row level security;
revoke all on table private.platform_audit_logs from public, anon, authenticated;
create index if not exists idx_platform_audit_created_at
  on private.platform_audit_logs(created_at desc);

create or replace function private.register_platform_tenant()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into private.platform_tenants(workspace_id,status,created_at,updated_at)
  values(new.id,'active',coalesce(new.created_at,now()),now())
  on conflict (workspace_id) do nothing;
  return new;
end;
$$;
revoke all on function private.register_platform_tenant() from public, anon, authenticated;

drop trigger if exists trg_register_platform_tenant on public.workspaces;
create trigger trg_register_platform_tenant
after insert on public.workspaces
for each row execute function private.register_platform_tenant();

create or replace function private.is_platform_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_user_id is not null and exists (
    select 1
    from private.platform_admins pa
    where pa.user_id = p_user_id
      and pa.is_active
  );
$$;
revoke all on function private.is_platform_admin(uuid) from public, anon;
grant execute on function private.is_platform_admin(uuid) to authenticated;

create or replace function private.require_platform_admin()
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;
  if not private.is_platform_admin(v_uid) then
    raise exception 'PLATFORM_ADMIN_REQUIRED';
  end if;
  return v_uid;
end;
$$;
revoke all on function private.require_platform_admin() from public, anon;
grant execute on function private.require_platform_admin() to authenticated;

create or replace function private.platform_admin_me_impl()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
begin
  if v_uid is null then
    return jsonb_build_object('authorized',false,'authenticated',false);
  end if;

  select pa.role into v_role
  from private.platform_admins pa
  where pa.user_id=v_uid and pa.is_active;

  if v_role is null then
    return jsonb_build_object('authorized',false,'authenticated',true);
  end if;

  return jsonb_build_object(
    'authorized',true,
    'authenticated',true,
    'user_id',v_uid,
    'role',v_role
  );
end;
$$;
revoke all on function private.platform_admin_me_impl() from public, anon;
grant execute on function private.platform_admin_me_impl() to authenticated;

create or replace function private.platform_admin_overview_impl()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform private.require_platform_admin();
  return jsonb_build_object(
    'companies_total',(select count(*) from private.platform_tenants),
    'companies_active',(select count(*) from private.platform_tenants where status='active'),
    'companies_onboarding',(select count(*) from private.platform_tenants where status='onboarding'),
    'companies_suspended',(select count(*) from private.platform_tenants where status='suspended'),
    'companies_archived',(select count(*) from private.platform_tenants where status='archived'),
    'users_total',(select count(*) from auth.users),
    'active_memberships',(select count(*) from public.workspace_members where is_active),
    'platform_admins_active',(select count(*) from private.platform_admins where is_active),
    'generated_at',now()
  );
end;
$$;
revoke all on function private.platform_admin_overview_impl() from public, anon;
grant execute on function private.platform_admin_overview_impl() to authenticated;

create or replace function private.platform_admin_companies_impl()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform private.require_platform_admin();

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'company_id',w.id,
        'name',w.name,
        'display_name',coalesce(p.display_name,w.name),
        'legal_name',p.legal_name,
        'status',pt.status,
        'owner_email',u.email,
        'active_members',(
          select count(*) from public.workspace_members m
          where m.workspace_id=w.id and m.is_active
        ),
        'created_at',w.created_at,
        'updated_at',pt.updated_at
      )
      order by w.created_at desc
    )
    from private.platform_tenants pt
    join public.workspaces w on w.id=pt.workspace_id
    join auth.users u on u.id=w.owner_user_id
    left join public.workspace_print_profiles p on p.workspace_id=w.id
  ),'[]'::jsonb);
end;
$$;
revoke all on function private.platform_admin_companies_impl() from public, anon;
grant execute on function private.platform_admin_companies_impl() to authenticated;

create or replace function private.platform_admin_audit_impl(p_limit integer default 30)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_limit integer := greatest(1,least(coalesce(p_limit,30),100));
begin
  perform private.require_platform_admin();
  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x.created_at desc)
    from (
      select pal.id,pal.action,pal.tenant_id,pal.summary,pal.created_at
      from private.platform_audit_logs pal
      order by pal.created_at desc
      limit v_limit
    ) x
  ),'[]'::jsonb);
end;
$$;
revoke all on function private.platform_admin_audit_impl(integer) from public, anon;
grant execute on function private.platform_admin_audit_impl(integer) to authenticated;

create or replace function private.platform_admin_enter_impl()
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid;
begin
  v_uid := private.require_platform_admin();
  insert into private.platform_audit_logs(actor_user_id,action,summary)
  values(v_uid,'control_plane_opened','Platform Admin opened the Avan Control Plane');
  return true;
end;
$$;
revoke all on function private.platform_admin_enter_impl() from public, anon;
grant execute on function private.platform_admin_enter_impl() to authenticated;

-- Exposed RPC wrappers remain SECURITY INVOKER. Privileged reads live only in private schema.
create or replace function public.platform_admin_me()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$ select private.platform_admin_me_impl(); $$;

create or replace function public.platform_admin_overview()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$ select private.platform_admin_overview_impl(); $$;

create or replace function public.platform_admin_companies()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$ select private.platform_admin_companies_impl(); $$;

create or replace function public.platform_admin_audit(p_limit integer default 30)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$ select private.platform_admin_audit_impl(p_limit); $$;

create or replace function public.platform_admin_enter()
returns boolean
language sql
security invoker
set search_path = ''
as $$ select private.platform_admin_enter_impl(); $$;

revoke all on function public.platform_admin_me() from public, anon;
revoke all on function public.platform_admin_overview() from public, anon;
revoke all on function public.platform_admin_companies() from public, anon;
revoke all on function public.platform_admin_audit(integer) from public, anon;
revoke all on function public.platform_admin_enter() from public, anon;

grant execute on function public.platform_admin_me() to authenticated;
grant execute on function public.platform_admin_overview() to authenticated;
grant execute on function public.platform_admin_companies() to authenticated;
grant execute on function public.platform_admin_audit(integer) to authenticated;
grant execute on function public.platform_admin_enter() to authenticated;

notify pgrst, 'reload schema';
commit;
