'use strict';
import { createSupabaseClient } from './src/infrastructure/supabase/supabase-client.js';
const client=createSupabaseClient({config:window.AVAN_CONFIG||{},storage:localStorage});
const params=new URLSearchParams(location.search);const sessionId=params.get('session');
const state=document.getElementById('svState'),content=document.getElementById('svContent'),title=document.getElementById('svTitle'),meta=document.getElementById('svMeta'),dataHost=document.getElementById('svData'),tabs=document.getElementById('svTabs'),refresh=document.getElementById('svRefresh');
let resource='overview';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fa=v=>Number(v||0).toLocaleString('fa-IR');
function faDate(v){if(!v)return'—';try{return new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return'—'}}
function setState(text,error=false){state.textContent=text;state.className=`sv-state${error?' error':''}`}
function renderOverview(d){const counts=d?.counts||{};const company=d?.company||{};dataHost.innerHTML=`<div class="sv-grid"><div class="sv-card"><span>شرکت</span><strong>${esc(company.display_name||'—')}</strong></div><div class="sv-card"><span>پلن</span><strong>${esc(company.plan_code||'—')}</strong></div><div class="sv-card"><span>وضعیت Tenant</span><strong>${esc(company.tenant_status||'—')}</strong></div>${Object.entries(counts).map(([k,v])=>`<div class="sv-card"><span>${esc(k)}</span><strong>${fa(v)}</strong></div>`).join('')}</div>`}
function renderRows(rows){if(!Array.isArray(rows)||!rows.length){dataHost.innerHTML='<div class="sv-empty">داده‌ای برای نمایش نیست.</div>';return}const cols=Object.keys(rows[0]);dataHost.innerHTML=`<table class="sv-table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function load(){if(!sessionId){setState('شناسه Support Session وجود ندارد.',true);return}refresh.disabled=true;try{const info=await client.rpc('platform_support_session_info',{p_session_id:sessionId});if(!info?.active){content.hidden=true;setState('این Support Session منقضی یا لغو شده است.',true);return}title.textContent=`Support Viewer — ${info.company_name||'شرکت'}`;meta.textContent=`فقط‌خواندنی · انقضا: ${faDate(info.expires_at)} · دلیل: ${info.reason||'—'}`;const result=await client.rpc('platform_support_read',{p_session_id:sessionId,p_resource:resource,p_limit:50});content.hidden=false;setState('Session معتبر است. همه خواندن‌ها در Audit پلتفرم ثبت می‌شوند.');if(resource==='overview')renderOverview(result?.data||{});else renderRows(result?.data||[])}catch(e){console.error(e);content.hidden=true;const m=String(e?.message||'');setState(m.includes('SUPPORT_SESSION_EXPIRED')?'Session منقضی شده است.':m.includes('SUPPORT_SESSION_REVOKED')?'Session لغو شده است.':'دسترسی Support Viewer مجاز نیست.',true)}finally{refresh.disabled=false}}
tabs?.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>{resource=b.dataset.resource;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));load()});refresh.onclick=load;load();