import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = rel => fs.readFileSync(new URL(`../${rel}`, import.meta.url), 'utf8');

const accessWrapper = read('rc11-access.js');
const supportWrapper = read('rc13-support-access.js');
const companyContext = read('rc13-company-context.js');
const audit = read('rc13-operational-audit.js');
const access = read('src/ui/settings/workspace-access-settings.js');
const support = read('src/ui/settings/support-access-settings.js');
const money = read('src/ui/money/money-settings-card.js');
const layout = read('src/ui/settings/settings-layout-v2.js');
const sw = read('sw.js');

assert.match(accessWrapper, /workspace-access-settings\.js/);
assert.match(supportWrapper, /support-access-settings\.js/);
assert.doesNotMatch(accessWrapper, /MutationObserver/,'legacy access wrapper must not reinstall a body-wide observer');
assert.doesNotMatch(supportWrapper, /MutationObserver/,'legacy support wrapper must not reinstall its private observer');
assert.match(access, /installUiLifecycle/);
assert.match(support, /installUiLifecycle/);
assert.doesNotMatch(access, /new MutationObserver|MutationObserver\s*\(/,'workspace access must use the central lifecycle, not a private DOM observer');
assert.doesNotMatch(support, /new MutationObserver|MutationObserver\s*\(/,'support access must use the central lifecycle, not a private DOM observer');
assert.doesNotMatch(access, /outerHTML\s*=|replaceWith\(/,'the access card shell must not be replaced after it mounts');
assert.doesNotMatch(support, /outerHTML\s*=|replaceWith\(/,'the support card shell must not be replaced after it mounts');
assert.match(access, /data-avan-access-body/);
assert.match(support, /data-avan-support-list/);
assert.match(access, /companyContext\.ensure\(\)/);
assert.match(access, /loadAccessModel\(forceAccess\)/);
assert.doesNotMatch(companyContext, /arrangeSettings|moveAfter|findCardByTitle/);
assert.doesNotMatch(companyContext, /new MutationObserver|MutationObserver\s*\(/);
assert.match(companyContext, /avan:page-rendered/);
assert.match(audit, /installUiLifecycle/);
assert.match(audit, /data-avan-audit-slot/);
assert.match(audit, /avan-audit-stable-shell/);
assert.doesNotMatch(audit, /new MutationObserver|MutationObserver\s*\(/);
assert.doesNotMatch(audit, /setTimeout\s*\(/);
assert.doesNotMatch(audit, /content\.(?:append|appendChild|insertAdjacentHTML)\s*\(/);
assert.match(layout, /data-avan-tax-slot/);
assert.match(layout, /data-avan-access-slot/);
assert.match(layout, /data-avan-support-slot/);
assert.match(layout, /data-avan-audit-slot/);
assert.match(layout, /data-avan-profile-slot/);
assert.match(layout, /min-height:410px/);
assert.match(layout, /min-height:190px/);
assert.match(layout, /min-height:330px/);
assert.match(layout, /max-height:420px/);
const taxIndex = layout.indexOf("const taxSlot = ensureSlot");
const accessIndex = layout.indexOf("const accessSlot = ensureSlot");
const supportIndex = layout.indexOf("const supportSlot = ensureSlot");
const auditIndex = layout.indexOf("const auditSlot = ensureSlot");
const profileIndex = layout.indexOf("const profileSlot = ensureSlot");
assert.ok(taxIndex >= 0 && taxIndex < accessIndex && accessIndex < supportIndex && supportIndex < auditIndex && auditIndex < profileIndex);
assert.match(layout, /#content > \[data-avan-company-profile\]/);
assert.match(layout, /#content > \[data-avan-operational-audit\]/);
assert.match(money, /MoneyRuntime\.isReady\(\)/);
assert.match(money, /MoneyRuntime\.snapshot\(\)/);
assert.match(money, /queueMicrotask/);
assert.doesNotMatch(money, /Lifecycle\.schedule\('money-settings-page'/);
assert.match(sw, /const CACHE='avan-staging-rc1-v\d+-[^']+'/);
assert.match(sw, /src\/ui\/settings\/workspace-access-settings\.js/);
assert.match(sw, /src\/ui\/settings\/support-access-settings\.js/);
assert.match(sw, /rc13-operational-audit\.js/);
assert.match(sw, /rc13-company-context\.js/);
console.log('settings-stable-shells.spec.mjs: PASS');
