import { createClient } from 'npm:@supabase/supabase-js@2.57.4';

const FEED_KEY_SHA256='9094131588783f2c603da7ced856661303f96c00913b1e687c3e4e30920d45c3';
async function sha256Hex(value:string){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-feed-key','Access-Control-Allow-Methods':'POST,OPTIONS'};
function backendKey(){let k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const s=Deno.env.get('SUPABASE_SECRET_KEYS');if(s){try{k=JSON.parse(s).default||k}catch{}}return k}
function safeRow(r:any){const allowed=['id','symbol','company_name','state','last_price','closing_price','yesterday_price','low_price','high_price','min_allowed','max_allowed','volume','value','buy_depth','sell_depth','best_bid','best_ask','sell_queue','buy_queue','fast_score','fast_probability','signal_accel','continuation_score','prob_2d','prob_3d','risk_score','qi','ofi','bid_stack_15s','ask_pull_15s','daily_rvol','rsi_5m','ema9_5m','ema21_5m','vwap','atr_5m','technical_score','microprice','absorption','cancellation_ratio','price_velocity','trade_accel','recovery','depth_ratio','queue_decay','momentum','real_flow_ratio','hunt_state','decision','entry_price','entry_low','entry_high','stop_loss','target_1','target_2','target_3','risk_reward','reason','snapshots','candles','raw_json'];const o:any={};for(const k of allowed)if(r?.[k]!==undefined)o[k]=r[k];o.id=String(o.id||'').trim();o.symbol=String(o.symbol||'').trim();o.company_name=String(o.company_name||'').trim();o.updated_at=new Date().toISOString();return o}
function safeUniverse(r:any){const o:any={ins_code:String(r?.ins_code??r?.id??r?.insCode??'').trim(),symbol:String(r?.symbol??r?.lVal18AFC??'').trim(),company_name:String(r?.company_name??r?.lVal30??'').trim(),isin:String(r?.isin??r?.cIsin??'').trim()||null,market:String(r?.market??r?.flowTitle??'').trim()||null,flow:Number.isFinite(Number(r?.flow))?Number(r.flow):null,asset_type:String(r?.asset_type??'نامشخص').trim(),source:String(r?.source??'tsetmc').trim(),is_active:r?.is_active!==false,last_seen_at:r?.last_seen_at||new Date().toISOString(),updated_at:new Date().toISOString(),metadata:(r?.metadata&&typeof r.metadata==='object')?r.metadata:{}};return o}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'method'}),{status:405,headers:{...cors,'Content-Type':'application/json'}});const feedKey=req.headers.get('x-feed-key')||'';if(!feedKey||await sha256Hex(feedKey)!==FEED_KEY_SHA256)return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:{...cors,'Content-Type':'application/json'}});try{const body=await req.json();const rows=Array.isArray(body?.rows)?body.rows:[],universe=Array.isArray(body?.universe)?body.universe:[];if(rows.length>800||universe.length>5000)return new Response(JSON.stringify({ok:false,error:'too many rows'}),{status:413,headers:{...cors,'Content-Type':'application/json'}});const url=Deno.env.get('SUPABASE_URL')||'',key=backendKey();if(!url||!key)throw new Error('backend credentials unavailable');const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const clean=rows.map(safeRow).filter((r:any)=>r.id&&r.symbol&&r.symbol!=='—');if(clean.length){const {error}=await db.from('stock_hunter_signals_v4').upsert(clean,{onConflict:'id'});if(error)throw error;const seed=clean.map((r:any)=>({ins_code:r.id,symbol:r.symbol,company_name:r.company_name,source:'signals',is_active:true,last_seen_at:r.updated_at,updated_at:new Date().toISOString()}));const {error:se}=await db.from('stock_hunter_universe_v4').upsert(seed,{onConflict:'ins_code'});if(se)throw se}
const uclean=universe.map(safeUniverse).filter((r:any)=>r.ins_code&&r.symbol);for(let i=0;i<uclean.length;i+=500){const {error:ue}=await db.from('stock_hunter_universe_v4').upsert(uclean.slice(i,i+500),{onConflict:'ins_code'});if(ue)throw ue}
const health={id:'local-agent',source:String(body?.source||'local-agent'),status:String(body?.status||'ok'),message:String(body?.message||''),symbols:clean.length,agent_version:String(body?.agent_version||''),last_feed_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error:he}=await db.from('stock_hunter_feed_health_v4').upsert(health,{onConflict:'id'});if(he)throw he;return new Response(JSON.stringify({ok:true,count:clean.length,universe_count:uclean.length}),{headers:{...cors,'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({ok:false,error:String((e as any)?.message||e)}),{status:500,headers:{...cors,'Content-Type':'application/json'}})}});
