'use strict';
const cfg=window.STOCK_HUNTER_CONFIG||{}, $=id=>document.getElementById(id), n=v=>{const x=Number(v);return Number.isFinite(x)?x:null}, fa=(v,d=2)=>n(v)==null?'—':Number(v).toLocaleString('fa-IR',{maximumFractionDigits:d}), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let rows=[],page=1,sound=true,seen=new Set(),currentDetail=null;const historyCache=new Map();
const columns=[
 ['symbol','نماد',true,17],['hunt','شکار',true,12],['decision','تصمیم',true,11],['fast','امتیاز لحظه‌ای',true,11],
 ['price','قیمت',true,10],['entry','ورود پیشنهادی',true,11],['target1','هدف اول',true,10],['stop','حد ضرر',true,10],
 ['accel','شتاب سیگنال',false,9],['p2','تداوم ۲ روزه',false,10],['p3','تداوم ۳ روزه',false,10],['risk','ریسک',false,8],
 ['qi','عدم‌تعادل صف',false,9],['ofi','جریان سفارش',false,9],['bidStack','انباشت خرید',false,9],['askPull','عقب‌نشینی فروش',false,9],['rvol','حجم نسبی',false,9],['details','جزئیات',true,7]
];
const defaultKeys=columns.filter(c=>c[2]).map(c=>c[0]);let visible=new Set(JSON.parse(localStorage.getItem('sh_columns_v407')||'null')||defaultKeys);
function parseArr(v){if(Array.isArray(v))return v;if(typeof v==='string'){try{const x=JSON.parse(v);return Array.isArray(x)?x:[]}catch{return[]}}return[]}
function norm(r){return{id:String(r.id),symbol:r.symbol||'—',company:r.company_name||'—',hunt:r.hunt_state||'عادی',decision:r.decision||'نخر',fast:+r.fast_score||0,fastProb:+r.fast_probability||0,accel:+r.signal_accel||0,cont:+r.continuation_score||0,p2:+r.prob_2d||0,p3:+r.prob_3d||0,risk:+r.risk_score||0,qi:+r.qi||0,ofi:+r.ofi||0,bidStack:+r.bid_stack_15s||0,askPull:+r.ask_pull_15s||0,rvol:+r.daily_rvol||0,last:+r.last_price||0,close:+r.closing_price||0,yesterday:+r.yesterday_price||0,rsi:+r.rsi_5m||0,ema9:+r.ema9_5m||0,ema21:+r.ema21_5m||0,vwap:+r.vwap||0,atr:+r.atr_5m||0,technical:+r.technical_score||0,micro:+r.microprice||0,abs:+r.absorption||0,cancel:+r.cancellation_ratio||0,pv:+r.price_velocity||0,tradeAccel:+r.trade_accel||0,recovery:+r.recovery||0,depthRatio:+r.depth_ratio||0,queueDecay:+r.queue_decay||0,momentum:+r.momentum||0,realFlow:+r.real_flow_ratio||0,entry:+r.entry_price||0,entryLow:+r.entry_low||0,entryHigh:+r.entry_high||0,stop:+r.stop_loss||0,t1:+r.target_1||0,t2:+r.target_2||0,t3:+r.target_3||0,rr:+r.risk_reward||0,reason:r.reason||'',updated:r.updated_at||'',candles:parseArr(r.candles)}}
function hc(v){return v==='شکار ویژه'?'special':v==='هشدار فوری'?'urgent':v==='شکار زودهنگام'?'early':v==='مستعد تداوم'?'continue':'watch'}function dc(v){return v.includes('خرید')?'buy':v==='ورود اولیه'?'early':v==='تحت نظر'?'watch':'no'}function rc(v){return v<40?'risk-low':v<65?'risk-mid':'risk-high'}
function cell(k,x){switch(k){case'symbol':return `<div class="symbol">${esc(x.symbol)}</div><div class="company">${esc(x.company)}</div>`;case'hunt':return `<span class="badge ${hc(x.hunt)}">${esc(x.hunt)}</span>`;case'decision':return `<span class="badge ${dc(x.decision)}">${esc(x.decision)}</span>`;case'fast':return `<b>${fa(x.fast,1)}</b><div class="company">احتمال ${fa(x.fastProb,1)}٪</div>`;case'price':return fa(x.last,0);case'entry':return fa(x.entry,0);case'target1':return `<span class="risk-low">${fa(x.t1,0)}</span>`;case'stop':return `<span class="risk-high">${fa(x.stop,0)}</span>`;case'accel':return fa(x.accel,1);case'p2':return `${fa(x.p2,1)}٪`;case'p3':return `${fa(x.p3,1)}٪`;case'risk':return `<span class="${rc(x.risk)}">${fa(x.risk,1)}</span>`;case'qi':return fa(x.qi,2);case'ofi':return fa(x.ofi,2);case'bidStack':return `${fa(x.bidStack,1)}٪`;case'askPull':return `${fa(x.askPull,1)}٪`;case'rvol':return x.rvol?`${fa(x.rvol,2)} برابر`:'—';case'details':return `<button class="detail-btn" data-id="${esc(x.id)}">نمایش</button>`;default:return'—'}}
function filtered(){const q=$('search').value.trim(),h=$('hunt').value,d=$('decision').value;return rows.filter(x=>{const huntOK=h?x.hunt===h:(x.hunt==='شکار ویژه'||x.hunt==='هشدار فوری');return huntOK&&(!q||x.symbol.includes(q)||x.company.includes(q))&&(!d||x.decision===d)}).sort((a,b)=>b.fast-a.fast)}
function render(){const a=filtered(),size=+$('pageSize').value||25,pages=Math.max(1,Math.ceil(a.length/size));if(page>pages)page=pages;const slice=a.slice((page-1)*size,page*size),cols=columns.filter(c=>visible.has(c[0]));$('thead').innerHTML='<tr><th style="width:42px">#</th>'+cols.map(c=>`<th style="width:${c[3]}%">${c[1]}</th>`).join('')+'</tr>';$('tbody').innerHTML=slice.length?slice.map((x,i)=>'<tr><td>'+(((page-1)*size+i+1).toLocaleString('fa-IR'))+'</td>'+cols.map(c=>`<td>${cell(c[0],x)}</td>`).join('')+'</tr>').join(''):`<tr><td colspan="${cols.length+1}">${$('hunt').value?'نمادی مطابق فیلتر انتخاب‌شده وجود ندارد.':'در حال حاضر نمادی در وضعیت شکار ویژه یا هشدار فوری وجود ندارد.'}</td></tr>`;$('pageInfo').textContent=`صفحه ${page.toLocaleString('fa-IR')} از ${pages.toLocaleString('fa-IR')} — ${a.length.toLocaleString('fa-IR')} نماد`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;renderMobile(slice);updateSummary();}
function renderMobile(a){$('mobileList').innerHTML=a.length?a.map(x=>`<article class="mobile-card"><div class="mobile-head"><div><div class="mobile-symbol">${esc(x.symbol)}</div><div class="company">${esc(x.company)}</div></div><div><span class="badge ${hc(x.hunt)}">${esc(x.hunt)}</span> <span class="badge ${dc(x.decision)}">${esc(x.decision)}</span></div></div><div class="mobile-metrics"><div><span>امتیاز</span><b>${fa(x.fast,1)}</b></div><div><span>قیمت</span><b>${fa(x.last,0)}</b></div><div><span>ورود</span><b>${fa(x.entry,0)}</b></div><div><span>هدف اول</span><b class="risk-low">${fa(x.t1,0)}</b></div><div><span>حد ضرر</span><b class="risk-high">${fa(x.stop,0)}</b></div></div><div class="mobile-foot"><span></span><button class="detail-btn" data-id="${esc(x.id)}">جزئیات</button></div></article>`).join(''):'<div class="alert-box">داده‌ای مطابق فیلتر فعلی وجود ندارد.</div>'}
function updateSummary(){$('specialCount').textContent=rows.filter(x=>x.hunt==='شکار ویژه').length.toLocaleString('fa-IR');$('urgentCount').textContent=rows.filter(x=>x.hunt==='هشدار فوری').length.toLocaleString('fa-IR');$('buyCount').textContent=rows.filter(x=>x.decision==='خرید قوی'||x.decision==='ورود اولیه').length.toLocaleString('fa-IR');const t=[...rows].filter(x=>x.hunt==='شکار ویژه'||x.hunt==='هشدار فوری').sort((a,b)=>b.fast-a.fast)[0];$('topSymbol').textContent=t?.symbol||'—';$('topMeta').textContent=t?`${t.company} — امتیاز ${fa(t.fast,1)}`:'—'}
function metric(l,v,c=''){return `<div class="metric"><span>${l}</span><b class="${c}">${v}</b></div>`}
function dailyCandles(x){const c=x.candles.map(z=>({t:+(z.t??z.time??0),open:+(z.open??z.priceFirst??0),high:+(z.high??z.priceMax??0),low:+(z.low??z.priceMin??0),close:+(z.close??z.pClosing??0),volume:+(z.volume??z.qTotTran5J??0)})).filter(z=>z.t&&z.high&&z.low&&z.close).sort((a,b)=>a.t-b.t);if(c.length<2)return[];const gaps=[];for(let i=1;i<c.length;i++)gaps.push(c[i].t-c[i-1].t);gaps.sort((a,b)=>a-b);const med=gaps[Math.floor(gaps.length/2)]||0;return med>=18*3600?c:[]}
function dEvenTs(v){const s=String(v||'');if(!/^\d{8}$/.test(s))return 0;return Date.UTC(+s.slice(0,4),+s.slice(4,6)-1,+s.slice(6,8))/1000}
async function fetchDailyHistory(x){const existing=dailyCandles(x);if(existing.length>=60)return existing;if(historyCache.has(x.id)){x.candles=historyCache.get(x.id);return dailyCandles(x)}const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),9000);try{const u=`https://cdn.tsetmc.com/api/ClosingPrice/GetClosingPriceDailyList/${encodeURIComponent(x.id)}/120`;const r=await fetch(u,{cache:'no-store',mode:'cors',signal:ctrl.signal,headers:{Accept:'application/json,text/plain,*/*'}});if(!r.ok)throw new Error('پاسخ نامعتبر تاریخچه');const j=await r.json(),a=Array.isArray(j?.closingPriceDaily)?j.closingPriceDaily:[];const c=a.map(z=>({t:dEvenTs(z.dEven),open:+z.priceFirst||0,high:+z.priceMax||0,low:+z.priceMin||0,close:+z.pClosing||+z.pDrCotVal||0,volume:+z.qTotTran5J||0})).filter(z=>z.t&&z.high&&z.low&&z.close).sort((a,b)=>a.t-b.t);if(c.length){x.candles=c;historyCache.set(x.id,c)}return c}catch{return existing}finally{clearTimeout(timer)}}
function midHL(a,p){if(a.length<p)return null;const s=a.slice(-p),hi=Math.max(...s.map(z=>z.high)),lo=Math.min(...s.map(z=>z.low));return(hi+lo)/2}
function atrDaily(a,p=14){if(a.length<p+1)return null;let s=0;for(let i=a.length-p;i<a.length;i++){const q=a[i],prev=a[i-1].close;s+=Math.max(q.high-q.low,Math.abs(q.high-prev),Math.abs(q.low-prev))}return s/p}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function nextTradingDates(count){const out=[];let d=new Date();while(out.length<count){d=new Date(d.getTime()+86400000);const wd=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tehran',weekday:'short'}).format(d);if(!['Thu','Fri'].includes(wd))out.push(new Intl.DateTimeFormat('fa-IR-u-ca-persian',{timeZone:'Asia/Tehran',month:'2-digit',day:'2-digit'}).format(d))}return out}