(() => {
'use strict';
const VERSION='4.0.1';
const cfg=window.STOCK_HUNTER_CONFIG||{};let rows=[],sound=true,seen=new Set();
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const N=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:null}, fa=v=>N(v)===null?'—':Number(v).toLocaleString('fa-IR',{maximumFractionDigits:2}), f1=v=>N(v)===null?'—':Number(v).toFixed(1), f2=v=>N(v)===null?'—':Number(v).toFixed(2);
const obj=v=>{if(v&&typeof v==='object'&&!Array.isArray(v))return v;if(typeof v==='string')try{return JSON.parse(v)}catch{}return{}};
function sources(r){return[r,obj(r.raw_json),obj(r.raw),obj(r.payload),obj(r.instrument)].filter(Boolean)}
function pick(r,...ks){for(const s of sources(r))for(const k of ks){if(s[k]!==undefined&&s[k]!==null&&String(s[k]).trim()!=='')return s[k];const z=Object.keys(s).find(q=>q.toLowerCase()===k.toLowerCase());if(z&&String(s[z]??'').trim()!=='')return s[z]}return null}
const num=(r,...k)=>N(pick(r,...k)), txt=(r,...k)=>String(pick(r,...k)??'').trim();
function norm(r,i){const fast=num(r,'fast_score','fastScore','fast')??0,cont=num(r,'continuation_score','continuationScore')??0,risk=num(r,'risk_score','riskScore')??0,accel=num(r,'signal_accel','signal_acceleration','signalAccel')??0;return{
 id:String(pick(r,'id','ins_code','insCode')??i),raw:r,
 symbol:txt(r,'symbol','ticker','lVal18AFC','instrumentName')||'—',company:txt(r,'company_name','companyNamePersian','companyName','lVal30')||'—',
 hunt:txt(r,'hunt_state','huntState')||((fast>=78&&cont>=72&&risk<=42)?'شکار ویژه':fast>=80||accel>=22?'هشدار فوری':fast>=65?'شکار زودهنگام':cont>=68?'مستعد تداوم':fast>=45||cont>=50?'رصد':'عادی'),
 decision:txt(r,'decision')||'نخر', fast, fastProb:num(r,'fast_probability','fastProbability')??0,accel,cont,p2:num(r,'prob_2d','prob_day2','prob2d')??0,p3:num(r,'prob_3d','prob_day3','prob3d')??0,risk,
 qi:num(r,'qi','queue_imbalance')??0,ofi:num(r,'ofi','order_flow_imbalance')??0,bidStack:num(r,'bid_stack_15s','bid_stack_15')??0,askPull:num(r,'ask_pull_15s','ask_pull_15')??0,rvol:num(r,'daily_rvol','rvol')??0,
 last:num(r,'last_price','last','pDrCotVal'),close:num(r,'closing_price','close','pClosing'),yesterday:num(r,'yesterday_price','yesterday'),rsi:num(r,'rsi_5m','rsi5'),ema9:num(r,'ema9_5m','ema9'),ema21:num(r,'ema21_5m','ema21'),vwap:num(r,'vwap'),atr:num(r,'atr_5m','atr5'),technical:num(r,'technical_score'),
 micro:num(r,'microprice'),abs:num(r,'absorption'),cancel:num(r,'cancellation_ratio'),pv:num(r,'price_velocity'),ta:num(r,'trade_accel','trade_acceleration'),
 entry:num(r,'entry_price'),entryLow:num(r,'entry_low'),entryHigh:num(r,'entry_high'),stop:num(r,'stop_loss'),t1:num(r,'target_1','target1'),t2:num(r,'target_2','target2'),t3:num(r,'target_3','target3'),rr:num(r,'risk_reward'),reason:txt(r,'reason'),updated:txt(r,'updated_at')};}
function hc(h){return h==='شکار ویژه'?'special':h==='هشدار فوری'?'urgent':h==='شکار زودهنگام'?'early':h==='مستعد تداوم'?'continue':'watch'}
function dc(d){return d.includes('خرید')?'buy':d==='ورود اولیه'?'early':d==='تحت نظر'?'watch':'no'}
function rc(r){return r<40?'risk-low':r<65?'risk-mid':'risk-high'}
function pct(x,y){return x&&y?(x/y-1)*100:0}
function selected(){const q=$('search').value.trim().toLowerCase(),h=$('hunt').value,mf=+$('minFast').value,mc=+$('minCont').value;return rows.filter(x=>x.fast>=mf&&x.p2>=mc&&(!h||x.hunt===h)&&(!q||x.symbol.toLowerCase().includes(q)||x.company.toLowerCase().includes(q)))}
function row(x,i){return `<tr><td>${i+1}</td><td><div class="symbol">${esc(x.symbol)}</div><div class="company">${esc(x.company)}</div></td><td><span class="badge ${hc(x.hunt)}">${esc(x.hunt)}</span></td><td><span class="badge ${dc(x.decision)}">${esc(x.decision)}</span></td><td><b>${f1(x.fast)}</b><div class="company">${f1(x.fastProb)}%</div></td><td>${f1(x.accel)}</td><td><b>${f1(x.p2)}%</b></td><td>${f1(x.p3)}%</td><td class="${rc(x.risk)}">${f1(x.risk)}</td><td>${f2(x.qi)}</td><td>${f2(x.ofi)}</td><td>${f1(x.bidStack)}%</td><td>${f1(x.askPull)}%</td><td>${x.rvol?f2(x.rvol)+'×':'…'}</td><td>${fa(x.last)}<div class="company">${x.last&&x.yesterday?f2(pct(x.last,x.yesterday))+'%':''}</div></td><td><button class="detail-btn" data-open="${esc(x.id)}">نمایش</button></td></tr>`}
function card(x){return `<article class="card"><div class="card-top"><div><div class="card-symbol">${esc(x.symbol)}</div><div class="company">${esc(x.company)}</div><div style="margin-top:7px"><span class="badge ${hc(x.hunt)}">${esc(x.hunt)}</span> <span class="badge ${dc(x.decision)}">${esc(x.decision)}</span></div></div><button class="detail-btn" data-open="${esc(x.id)}">جزئیات</button></div><div class="card-scores"><div><span>Fast</span><b>${f1(x.fast)}</b></div><div><span>۲ روز</span><b>${f1(x.p2)}%</b></div><div><span>۳ روز</span><b>${f1(x.p3)}%</b></div><div><span>Risk</span><b class="${rc(x.risk)}">${f1(x.risk)}</b></div></div></article>`}
function render(){const a=selected();$('tbody').innerHTML=a.length?a.map(row).join(''):'<tr><td colspan="16">داده‌ای مطابق فیلتر موجود نیست.</td></tr>';$('mobileList').innerHTML=a.length?a.map(card).join(''):'<div class="notice">داده‌ای مطابق فیلتر موجود نیست.</div>';$('specialCount').textContent=rows.filter(x=>x.hunt==='شکار ویژه').length.toLocaleString('fa-IR');$('urgentCount').textContent=rows.filter(x=>x.hunt==='هشدار فوری').length.toLocaleString('fa-IR');$('buyCount').textContent=rows.filter(x=>x.decision.includes('خرید')||x.decision==='ورود اولیه').length.toLocaleString('fa-IR');const t=rows[0];$('topSymbol').textContent=t?.symbol||'—';$('topMeta').textContent=t?`Fast ${f1(t.fast)} • ${t.company}`:'—';$('fastVal').textContent=$('minFast').value;$('contVal').textContent=$('minCont').value;}
function m(label,value,cls=''){return `<div class="metric"><span>${label}</span><b class="${cls}">${value??'—'}</b></div>`}
function openDetail(id){const x=rows.find(r=>r.id===String(id));if(!x)return;$('dSymbol').textContent=x.symbol;$('dCompany').textContent=x.company;$('detailBody').innerHTML=`<div class="detail-grid"><div class="section-title">هویت و تصمیم</div>${m('نماد',esc(x.symbol))}${m('نام شرکت',esc(x.company))}${m('وضعیت شکار',esc(x.hunt))}${m('تصمیم',esc(x.decision))}<div class="section-title">Fast / Microstructure</div>${m('Fast Score',f1(x.fast))}${m('Fast Probability',f1(x.fastProb)+'%')}${m('Signal Accel',f1(x.accel))}${m('QI',f2(x.qi))}${m('OFI',f2(x.ofi))}${m('Bid Stack 15s',f1(x.bidStack)+'%')}${m('Ask Pull 15s',f1(x.askPull)+'%')}${m('Microprice',fa(x.micro))}${m('Absorption',f1(x.abs)+'%')}${m('Cancellation',f1(x.cancel)+'%')}${m('Price Velocity',f2(x.pv))}${m('Trade Accel',f1(x.ta))}<div class="section-title">Continuation / Risk</div>${m('Continuation',f1(x.cont))}${m('2-Day',f1(x.p2)+'%')}${m('3-Day',f1(x.p3)+'%')}${m('Risk',f1(x.risk),rc(x.risk))}<div class="section-title">تکنیکال</div>${m('RSI 5m',f1(x.rsi))}${m('EMA9',fa(x.ema9))}${m('EMA21',fa(x.ema21))}${m('VWAP',fa(x.vwap))}${m('ATR 5m',fa(x.atr))}${m('Technical Score',f1(x.technical))}${m('Daily RVOL',x.rvol?f2(x.rvol)+'×':'—')}<div class="section-title">برنامه معامله</div>${m('ورود پیشنهادی',fa(x.entry))}${m('بازه ورود',`${fa(x.entryLow)} تا ${fa(x.entryHigh)}`)}${m('حد ضرر',fa(x.stop),'risk-high')}${m('هدف ۱',fa(x.t1),'risk-low')}${m('هدف ۲',fa(x.t2),'risk-low')}${m('هدف ۳',fa(x.t3),'risk-low')}${m('R/R',f2(x.rr))}<div class="detail-text"><b>منطق:</b> ${esc(x.reason||'Fast/Microstructure + Continuation + Risk')}</div></div>`;$('detailDialog').showModal();}
function headers(){const k=cfg.SUPABASE_PUBLISHABLE_KEY||cfg.publishableKey||'';return{apikey:k,Accept:'application/json'}}
async function load(){const url=String(cfg.SUPABASE_URL||cfg.supabaseUrl||'').replace(/\/$/,'');const key=cfg.SUPABASE_PUBLISHABLE_KEY||cfg.publishableKey||'';if(!url||!key||url.includes('__')){$('feedDot').className='dot bad';$('feedState').textContent='Supabase تنظیم نشده';return}try{const r=await fetch(`${url}/rest/v1/${cfg.TABLE||'stock_hunter_signals_v4'}?select=*&order=fast_score.desc&limit=250`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();rows=d.map(norm).sort((a,b)=>b.fast-a.fast||a.risk-b.risk);$('feedDot').className='dot ok';$('feedState').textContent='داده زنده';$('scanTimes').textContent=new Date().toLocaleTimeString('fa-IR');const pos=rows.filter(x=>x.last&&x.yesterday&&x.last>=x.yesterday).length;$('regime').textContent=rows.length&&pos/rows.length>.58?'مثبت':rows.length&&pos/rows.length<.42?'منفی':'متعادل';$('breadth').textContent=rows.length?`عرض بازار ${Math.round(pos/rows.length*100)}٪`:'—';$('alertBox').hidden=true;render();const urgent=rows.filter(x=>x.hunt==='شکار ویژه'||x.hunt==='هشدار فوری');if(sound&&urgent.some(x=>!seen.has(x.id))){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=930;g.gain.value=.04;o.start();o.stop(a.currentTime+.15)}catch{}}urgent.forEach(x=>seen.add(x.id));}catch(e){$('feedDot').className='dot bad';$('feedState').textContent='خطا در دریافت داده';$('alertBox').hidden=false;$('alertBox').textContent=e.message;}}
function csv(){const h=['نماد','نام شرکت','شکار','تصمیم','Fast','2-Day','3-Day','Risk','QI','OFI'];const a=[h,...selected().map(x=>[x.symbol,x.company,x.hunt,x.decision,x.fast,x.p2,x.p3,x.risk,x.qi,x.ofi])];const blob=new Blob(['\ufeff'+a.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const u=URL.createObjectURL(blob),el=document.createElement('a');el.href=u;el.download='stock-hunter-v4.csv';el.click();URL.revokeObjectURL(u)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openDetail(b.dataset.open)});$('closeDetail').onclick=()=>$('detailDialog').close();$('scanBtn').onclick=load;$('exportBtn').onclick=csv;$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'🔔 هشدار روشن':'🔕 هشدار خاموش'};for(const id of ['search','hunt','minFast','minCont'])$(id).addEventListener(id==='search'?'input':'change',render);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=4.0.1').catch(()=>{});load();setInterval(load,5000);window.StockHunterV4={norm,openDetail,version:VERSION};
})();
