// Stock Hunter source PWA 4.3.3 — network-first with installable offline shell.
// Frozen Hunt 4.1.6 scoring/runtime semantics are untouched.
const CACHE_PREFIX='shikar-sahm-v4-';
const CACHE=CACHE_PREFIX+'4.3.3-pwa1';
const STATIC=[
  './','./index.html','./offline.html','./manifest.webmanifest','./icon.svg',
  './styles.css','./extra.css','./forecast-v415.css','./neutral-theme-v416.css','./ux-v421.css','./ux-nav-v433.css','./decision-shell-v428.css','./pwa-v433.css',
  './app-core.js','./app-forecast.js','./app-runtime.js','./app-universe.js','./app-hotfix-v410.js','./app-integrated-v410.js','./app-integrated-summary-v410.js','./app-explain-v411.js','./app-forecast-bridge-v414.js','./app-forecast-trend-v415.js','./app-forecast-validation-v430.js','./app-theme-v412.js','./app-session-v413.js','./app-hunt-v416.js','./hunt-runtime-core-v417.js','./app-runtime-router-v417.js','./app-hunt-hierarchy-v416.js','./app-universal-search-v416.js','./app-eod-v416.js','./app-hunt-carry-v416.js','./app-hunt-timeline-v416.js','./app-ai-assistant-v417.js','./app-professional-detail-v420.js','./workspace-v420.js',
  './ux-common-v421.js','./ux-shell-v421.js','./decision-shell-v428.js','./research-lab-v416.css','./research-common-v416.js','./research-tools-v417.js','./data-export-v418.js','./locale-ui-v419.js','./pwa-v433.js',
  './hunt-journey-v416.html','./hunt-journey-v416.js','./market-replay-v416.html','./market-replay-v416.js','./replay-catalog-resilience-v431.js','./replay-session-v433.js','./replay-visual-v432.js','./replay-visual-v432.css','./replay-visual-v433.js','./replay-visual-v433.css','./backtest-lab-v416.html','./backtest-lab-v416.js','./missed-opportunities-v416.html','./missed-opportunities-v416.js','./alerts-center-v416.html','./alerts-center-v416.js','./reliability-v416.html','./reliability-v416.js','./strategy-builder-v417.html','./strategy-builder-v417.js','./professional-center-v420.html','./professional-center-v420.js','./professional-v420.css','./ai-center-v417.html','./ai-center-v417.js','./performance.html','./performance-v416.js','./config.js'
];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil((async()=>{const cache=await caches.open(CACHE);await Promise.allSettled(STATIC.map(async url=>{try{const r=await fetch(url,{cache:'reload'});if(r.ok)await cache.put(url,r.clone());}catch{}}));})());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith(CACHE_PREFIX)&&k!==CACHE)await caches.delete(k);if(self.registration.navigationPreload)try{await self.registration.navigationPreload.enable();}catch{}await self.clients.claim();})());});
async function networkFirst(request,fallback){const cache=await caches.open(CACHE);try{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),5500);try{const r=await fetch(request,{cache:'no-cache',signal:ctrl.signal});if(r.ok)cache.put(request,r.clone()).catch(()=>{});return r;}finally{clearTimeout(timer);}}catch{return(await cache.match(request,{ignoreSearch:true}))||(fallback?await cache.match(fallback,{ignoreSearch:true}):null)||Response.error();}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const u=new URL(request.url);if(u.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(networkFirst(request,'./offline.html'));return;}if(['script','style','image','font','manifest'].includes(request.destination)||/\.(?:js|css|png|svg|webmanifest)$/i.test(u.pathname))event.respondWith(networkFirst(request));});
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=new URL(event.notification?.data?.url||'alerts-center-v416.html',self.location.href).href;event.waitUntil((async()=>{const list=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of list){if(client.url===target||client.url.startsWith(target.split('?')[0])){await client.focus();return;}}if(self.clients.openWindow)await self.clients.openWindow(target);})());});
self.addEventListener('push',event=>{let data={};try{data=event.data?event.data.json():{};}catch{data={body:event.data?.text?.()||''};}const title=data.title||'شکارچی سهم',options={body:data.body||'رخداد تازه شکار ثبت شد.',icon:data.icon||'icon.svg',badge:data.badge||'icon.svg',tag:data.tag||'stock-hunter-cloud-push',renotify:false,data:data.data||{url:'alerts-center-v416.html'}};event.waitUntil(self.registration.showNotification(title,options));});
